### ISSUE TITLE
Add support for typed arrays

### ISSUE THREAD

**Issue by veged** [bem/jsd#20]
`Array[MyClass]`

**Comment by SevInf** [comment]
Why not [`MyClass[]`](http://usejsdoc.org/tags-type.html)?

**Comment by veged** [comment]
separate issue for complex cases — https://github.com/bem/jsdoc/issues/49

**Comment by veged** [comment]
@SevInf it allow to unify cases: `Array[String]`, `Array[Array[String]]` (and also looks much more convenient with Haskell notation ;-))
