### ISSUE TITLE
Add support for bem-oriented tags

### ISSUE THREAD

**Issue by dfilatov** [bem/jsd#38]
### Documenting of BEM blocks and elems with mods

For explicit declare of BEM block:

``` js
/**
 * @class my-block
 * @bem my-block
 */
```

For explicit declare of BEM elem:

``` js
/**
 * @class my-block__my-elem
 * @bem my-block__my-elem
 */
```

For explicit declare of BEM block with mod with single val:

``` js
/**
 * @class my-block
 * @bem my-block_my-mod_my-val
 */
```

For explicit declare of BEM block with mod with multi vals:

``` js
/**
 * @class my-block
 * @bem my-block_my-mod_my-val1_my-val2
 */
```

For implicit declare of any BEM item (it will be parsed from source):

``` js
/**
 * @class my-block
 * @bem
 */
```
### Documenting of JS params

``` js
/**
 * @class my-block
 * @bem
 * @param {String} p1 Param 1 description
 * @param {Boolean} p2 Param 2 description
 */
```
### Documenting of possible BEM mods and vals

``` js
/**
 * @class my-block
 * @bem
 * @bemmod my-mod1 My simple mod description
 * @bemmod my-mod My mod with vals description
 * @bemval my-val1 My val 1 description
 * @bemval my-val2 My val 2 description
 */
```

**Comment by arikon** [comment]
@dfilatov @veged @SevInf Когда мы только начали обсуждать тегирование БЭМ-блоков, мы рассматривали вариант с `@bem` и нам он показался сложным для чтения и понимания. Вариант с раздельными `@block`, `@mod` и `@val` кажется проще.

> ### Documenting of JS params
> 
> ``` js
> /**
>  * @class my-block
>  * @bem
>  * @param {String} p1 Param 1 description
>  * @param {Boolean} p2 Param 2 description
>  */
> ```

Здесь мы думали про `@jsparam`, потому что, если я не ошибаюсь, эти параметры передаются в конструктор блока не виде позиционных аргументов, а в виде ключей хеша. Или я ошибаюсь?

> ### Documenting of possible BEM mods and vals
> 
> ``` js
> /**
>  * @class my-block
>  * @bem
>  * @bemmod my-mod1 My simple mod description
>  * @bemmod my-mod My mod with vals description
>  * @bemval my-val1 My val 1 description
>  * @bemval my-val2 My val 2 description
>  */
> ```

Про это есть вопросы. Чем это описание модификаторов и их значений будет отличаться от описанных в файлах `title.txt`?

PS: пожалуйста, добавляйте mention, когда будете отвечать

**Comment by veged** [comment]
раздельные `@mod` и `@val` конфликтуют с тегами для указания возможных значений модификаторов

отдельное от `.title.txt` указание возможных значений модификаторов нужно для того, чтобы показать, что именно js на эти модификаторы существует

да, параметры передаются в виде хеша — поэтому позиционность не важна, важны только имена и подходит `@param`

**Comment by SevInf** [comment]
Можно ли такую запись:

``` javascript
/**
My mod
@bem block_elem_val
*/
```

сделать сокрашением для:

``` javascript
/**
My mod
@bemblock block
@bemmod mod
@bemval val
*/
```

Когда описываемая сущность это что-то вроде `bem_mod_val`, короткая форма легко читается и просто понять, что есть блок, что модификатор, а что его значение. А вот когда мы описываем что-то вроде `my-awesome-block_cool-modifier_amazing-value` глаза постоянно спотыкаются о `-` и читается это не очень легко.

И в чем смысл записи `@class my-block`? Мы ведь не можем сделать `new my-block()` и получить экземпляр класса. Кажется, что простого `@class` достаточно, а имя сущности и так уже бэм-ориентированными тегами описано.

**Comment by SevInf** [comment]
> да, параметры передаются в виде хеша — поэтому позиционность не важна, важны только имена и подходит @param

Почему это он подходит если для всех остальных кейсов использования `@param` позиционность как раз-таки важна? Нельзя вызвать функцию, передав ей параметры в другом порядке или в сигнатуре слушателя события описать параметры не в том порядке, в каком они отправлены.

**Comment by dfilatov** [comment]
@SevInf, про сокращенную запись, это разные вещи, первое это описание декларируемой bem-сущности, а второе -- описание модификаторов, которые ты можешь этой сущности поставить из js.
Посмотри на https://github.com/bem/jsdoc/blob/master/test/smoke/checkbox.js для примера.

**Comment by SevInf** [comment]
@dfilatov, то есть это по сути что-то близкое к ныне покойному `@modhandler`? Насколько я понял, мы договорились до того что из документации самого модификатора (`.title.txt`, `jsdoc` самого модификатора) должно быть ясно все, что пользователя может интересовать, а обработчики js - это нечто приватное.

**Comment by dfilatov** [comment]
@SevInf, нет это все-таки другое. Мы декларируем те модификаторы, которые можно менять в рантайме у этого блока (каких-то специфических обработчиков может и не быть, вполне возможно, что хватит только дефолтного поведения). По сути, декларируем допустимые варианты вызова метода `setMod`.

**Comment by veged** [comment]
@SevInf позиционность параметров никак не мешает — в финальном тексте они так и так идут в каком-то порядке, а мы нигде не говорим, что этот порядок (в случае с параметрами блока) что-то означает

**Comment by veged** [comment]
@SevInf `my-awesome-block_cool-modifier_amazing-value` — файлы и селекторы мы так называем и ничего, все живы ;-) а плодить вербозность ещё когда тегов не хватает под все задачи, мне кажется не стоит

**Comment by arikon** [comment]
@veged @dfilatov Про js параметры мы придумали такой способ:

``` js
/**
@property params.param1  Desc of param1
@property params.param2  Desc of param2
@property params.param3  Desc of param3
*/
```

Этот докблок указывается внутри `BEM.DOM.decl()`. Объяснение такое, что внутри js кода важно знать, какие параметры блока доступны для использования изнутри, а не для передачи снаружи.

**Comment by veged** [comment]
@arikon подстрока `params.` не несёт никакой полезной информации

снаружи и внутри параметры одинаковые

**Comment by arikon** [comment]
@veged Это отсылка к `this.params`. Параметры инстанса блока ведь там хранятся?

**Comment by veged** [comment]
@arikon они хранятся в в `this.params` так же как были переданы (ну если их никто явно не ломал) — вообще понятие параметров блока достаточно фундаментальное, чтобы не хотеть отражать эти детали, что сначало оно приходит так, а потом хранится иначе (это всё общее, на уровне базовой документации про i-bem)
